/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Empleado;
import Conexion.*;
import DAO.*;
import Tabla.*;
import VO.*;
import GUI.Empleado.*;
import GUI.Estudiante.*;
import GUI.Secretario.*;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Anita
 */
public class NuevoPedidoInsumo extends javax.swing.JPanel {

    /**
     * Creates new form NuevoPedidoInsumo
     */
    public NuevoPedidoInsumo() {
        initComponents();
        tabla(TablaProductos);
    }
    
    DefaultTableModel model = new DefaultTableModel();
    
    public void tabla(JTable visor){

        model.addColumn("Productos");
        model.addColumn("Cantidad");
        
        JTableHeader header = TablaProductos.getTableHeader();
        header.setBackground(Color.decode("#990000"));
        header.setForeground(Color.white);
        TablaProductos.setOpaque(true);
        TablaProductos.setFillsViewportHeight(true);
        TablaProductos.setBackground(Color.decode("#990000"));
        visor.setModel(model);
    }
    
    public void agregar(){
        model.addRow( new Object[]{
        CampoNombreProducto.getText(), txtcantu.getText()
        });
    }
    
    public void eliminar(){
        int fila = TablaProductos.getSelectedRow();
        model.removeRow(fila);
    }
    
    public void agregarPedidoBD(){
        /*
        //se obtienen los datos de los campos ingresados
        String fecha = txtfecha.getText();
        String dni = txtdni.getText();
        String area = txtarea.getText();
        
        try{
            if(fecha.equals("") ||dni.equals("") ||area.equals("")){
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
            }else{
                String sql = "insert into pedidoinsumos(dni,fecha,area,estado) values('"+ dni + "','" + fecha + "','" + area +"', 'En evaluación')";
                System.out.println(sql);
                
                //Abro conexión con la base de datos
                try{
                Conexion con = new Conexion();
                Connection conexion = con.conectar();
                Statement st;
                st = conexion.createStatement();
                st.executeUpdate(sql);
                
                System.out.println("Registro creado");
                
                
                //Añado a la base de datos los productos de la lista que figura en tabla
                
                for (int i = 0; i < TablaProductos.getRowCount(); i++) {
                    
                    //Obtengo la clave primaria del pedido creado en la Bd
                    String sqlCod = "Select codpedido from pedidoinsumos p where p.fecha = ('"+ fecha + "')";
                    ResultSet rs = st.executeQuery(sqlCod);
                    rs.next();
                    //rs.getString(1);
                    System.out.println(rs.getString(1));
                    
                    //System.out.println("Registro número: "+i);
                    System.out.println("Producto: "+TablaProductos.getValueAt(i, 0));
                    System.out.println("Cantidad: "+TablaProductos.getValueAt(i, 1));
                    String sql1 = "insert into insumos(codpedido, cantidad,nombreinsumo) values("+ rs.getString(1) + ",'" + TablaProductos.getValueAt(i, 0) + "','" + TablaProductos.getValueAt(i, 1) +"')";
                    st.executeUpdate(sql1);
                                    
                }
                }catch(SQLException e){
                    System.out.println(e.toString());
                }
                
                
                JOptionPane.showMessageDialog(null, "Nuevo Pedido Registrado");
                
                
                
            }
        }catch(Exception e){
        }
        
   */ }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtarea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CantUnidades = new javax.swing.JLabel();
        CampoNombreProducto = new javax.swing.JTextField();
        txtcantu = new javax.swing.JTextField();
        AniadirProducto = new javax.swing.JButton();
        EliminarProducto = new javax.swing.JButton();
        btnenviar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 0, 0));
        setPreferredSize(new java.awt.Dimension(768, 677));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Realizar Pedido de Insumos");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha");

        txtfecha.setText("DD/MM/AA");
        txtfecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Área donde se van a destinar los insumos");

        txtdni.setText("12345678");
        txtdni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtarea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre del Producto");

        CantUnidades.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        CantUnidades.setForeground(new java.awt.Color(255, 255, 255));
        CantUnidades.setText("Cantidad de Unidades");

        CampoNombreProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtcantu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AniadirProducto.setText("Añadir Producto");
        AniadirProducto.setBorderPainted(false);
        AniadirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AniadirProductoActionPerformed(evt);
            }
        });

        EliminarProducto.setText("Eliminar Producto");
        EliminarProducto.setBorderPainted(false);
        EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProductoActionPerformed(evt);
            }
        });

        btnenviar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnenviar.setForeground(new java.awt.Color(153, 0, 0));
        btnenviar.setText("Enviar");
        btnenviar.setBorderPainted(false);
        btnenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnenviarMouseClicked(evt);
            }
        });

        btnvolver.setBackground(new java.awt.Color(153, 0, 0));
        btnvolver.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(255, 255, 255));
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-hacia-atras.png"))); // NOI18N
        btnvolver.setText("Volver atrás");
        btnvolver.setBorderPainted(false);
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        TablaProductos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TablaProductos.setForeground(new java.awt.Color(255, 255, 255));
        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaProductos.setShowHorizontalLines(true);
        jScrollPane2.setViewportView(TablaProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvolver)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtarea)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(CampoNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AniadirProducto)
                                        .addGap(26, 26, 26)
                                        .addComponent(EliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CantUnidades)
                                    .addComponent(txtcantu, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CantUnidades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcantu)
                    .addComponent(CampoNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AniadirProducto)
                    .addComponent(EliminarProducto))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnvolver, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnenviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProductoActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_EliminarProductoActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    private void AniadirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AniadirProductoActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_AniadirProductoActionPerformed

    private void btnenviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnenviarMouseClicked
        // TODO add your handling code here:
        agregarPedidoBD();
    }//GEN-LAST:event_btnenviarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AniadirProducto;
    public javax.swing.JTextField CampoNombreProducto;
    private javax.swing.JLabel CantUnidades;
    public javax.swing.JButton EliminarProducto;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnenviar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField txtarea;
    public javax.swing.JTextField txtcantu;
    javax.swing.JTextField txtdni;
    public javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables

    
}
