/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import GUI.Estudiante.PrincipalEstudiante;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import Conexion.*;
import DAO.*;
import Tabla.*;
import VO.*;
import GUI.Empleado.*;
import GUI.Estudiante.*;
import GUI.Secretario.*;


/**
 *
 * @author dgera
 */
public class Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form MisInscripcioness
     */
    public Configuracion() {
       /* initComponents();
        Usuario usuarioActivo = Sesion.getUsuarioActual();
        lblUsername.setText(usuarioActivo.getNombre());
        nombre.setText(usuarioActivo.getNombre());
        apellido.setText(usuarioActivo.getApellido());
        dni.setText(usuarioActivo.getDni());
        ciudad.setText(usuarioActivo.getCiudad());
        direccion.setText(usuarioActivo.getDireccion());*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        icono = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        btnborrar = new javax.swing.JPanel();
        txtborrar = new javax.swing.JLabel();
        btnaplicar = new javax.swing.JPanel();
        txtaplicar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.setText("Nombre");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 263, 335, -1));

        apellido.setText("Apellido");
        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });
        add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 303, 335, -1));

        ciudad.setText("Ciudad");
        add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 383, 335, -1));

        dni.setForeground(new java.awt.Color(153, 153, 153));
        dni.setText("DNI");
        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });
        add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 343, 335, -1));

        direccion.setText("Direccion");
        add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 423, 335, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/perfil (1).png"))); // NOI18N
        add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 112));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¡BIENVENIDO DE VUELTA!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setForeground(new java.awt.Color(153, 0, 51));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("UserName");
        lblUsername.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lblUsernameComponentAdded(evt);
            }
        });
        lblUsername.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblUsernamePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 450, 50));

        btnborrar.setBackground(new java.awt.Color(255, 255, 255));
        btnborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtborrar.setBackground(new java.awt.Color(255, 255, 255));
        txtborrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtborrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtborrar.setText("Borrar Cuenta");
        txtborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtborrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnborrarLayout = new javax.swing.GroupLayout(btnborrar);
        btnborrar.setLayout(btnborrarLayout);
        btnborrarLayout.setHorizontalGroup(
            btnborrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtborrar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnborrarLayout.setVerticalGroup(
            btnborrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 120, -1));

        btnaplicar.setBackground(new java.awt.Color(255, 255, 255));
        btnaplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtaplicar.setBackground(new java.awt.Color(255, 255, 255));
        txtaplicar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtaplicar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtaplicar.setText("Aplicar Cambios");
        txtaplicar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtaplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtaplicarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnaplicarLayout = new javax.swing.GroupLayout(btnaplicar);
        btnaplicar.setLayout(btnaplicarLayout);
        btnaplicarLayout.setHorizontalGroup(
            btnaplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtaplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        btnaplicarLayout.setVerticalGroup(
            btnaplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtaplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(btnaplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsernamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblUsernamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lblUsernamePropertyChange

    private void lblUsernameComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lblUsernameComponentAdded

    }//GEN-LAST:event_lblUsernameComponentAdded

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void txtborrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtborrarMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Los datos se actualizaron con éxito!", "Configuración", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        PrincipalEstudiante principalE = new PrincipalEstudiante();
        principalE.setVisible(true);
        principalE.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
                frame.setVisible(false);
                frame.dispose();
        }
    }//GEN-LAST:event_txtborrarMousePressed

    private void txtaplicarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtaplicarMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Los datos se actualizaron con éxito!", "Configuración", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        PrincipalEstudiante principalE = new PrincipalEstudiante();
        principalE.setVisible(true);
        principalE.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if (frame != null) {
            frame.setVisible(false);
            frame.dispose();
        }
    }//GEN-LAST:event_txtaplicarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JPanel btnaplicar;
    private javax.swing.JPanel btnborrar;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel txtaplicar;
    private javax.swing.JLabel txtborrar;
    // End of variables declaration//GEN-END:variables
}
