/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dgera
 */
public class FormularioRegistro extends javax.swing.JFrame {

    /**
     * Creates new form FormularioReg
     */
    public FormularioRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        localidad = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        dni = new javax.swing.JTextField();
        fem = new javax.swing.JRadioButton();
        mas = new javax.swing.JRadioButton();
        email = new javax.swing.JTextField();
        barrio = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        facultad = new javax.swing.JComboBox<>();
        carrera = new javax.swing.JComboBox<>();
        nacimiento = new com.toedter.calendar.JDateChooser();
        pais = new javax.swing.JTextField();
        provincia = new javax.swing.JTextField();
        legajo = new javax.swing.JTextField();
        anioIng = new com.toedter.calendar.JYearChooser();
        jLabel1 = new javax.swing.JLabel();
        iconoenviar = new javax.swing.JLabel();
        txtenviar = new javax.swing.JLabel();
        iconoborrar = new javax.swing.JLabel();
        txtborrar = new javax.swing.JLabel();
        txtatras = new javax.swing.JLabel();
        iconatras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FORMULARIO DE REGISTRO");

        direccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(204, 204, 204));
        direccion.setText("Ingrese su direccion");
        direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                direccionMousePressed(evt);
            }
        });
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        localidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        localidad.setForeground(new java.awt.Color(204, 204, 204));
        localidad.setText("Ingrese su localidad");
        localidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                localidadMousePressed(evt);
            }
        });
        localidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localidadActionPerformed(evt);
            }
        });

        celular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        celular.setForeground(new java.awt.Color(204, 204, 204));
        celular.setText("Ingrese su celular");
        celular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                celularMousePressed(evt);
            }
        });

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(204, 204, 204));
        nombre.setText("Ingrese su nombre");
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreMousePressed(evt);
            }
        });

        dni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dni.setForeground(new java.awt.Color(204, 204, 204));
        dni.setText("Ingrese su DNI");
        dni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dniMousePressed(evt);
            }
        });
        dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniActionPerformed(evt);
            }
        });

        fem.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(fem);
        fem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fem.setForeground(new java.awt.Color(255, 255, 255));
        fem.setText("Feminino");

        mas.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(mas);
        mas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("Masculino");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(204, 204, 204));
        email.setText("Ingrese su e-mail");
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        barrio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        barrio.setForeground(new java.awt.Color(204, 204, 204));
        barrio.setText("Ingrese su barrio");
        barrio.setToolTipText("");
        barrio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barrioMousePressed(evt);
            }
        });
        barrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barrioActionPerformed(evt);
            }
        });

        apellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        apellido.setForeground(new java.awt.Color(204, 204, 204));
        apellido.setText("Ingrese su apellido");
        apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                apellidoMousePressed(evt);
            }
        });

        jRadioButton3.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Otro");

        facultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facultad de Ciencias Exactas y Tecnológicas", "Facultad de Ciencias Sociales y Humanidades", "Facultad de Agronomía y Agroindustria", "Facultad de Ciencias Médicas", "Facultad de Ciencias Forestales" }));
        facultad.setSelectedIndex(-1);
        facultad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facultadMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                facultadMousePressed(evt);
            }
        });
        facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultadActionPerformed(evt);
            }
        });

        carrera.setToolTipText("");

        pais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pais.setForeground(new java.awt.Color(204, 204, 204));
        pais.setText("Ingrese su pais");
        pais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paisMousePressed(evt);
            }
        });
        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });

        provincia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        provincia.setForeground(new java.awt.Color(204, 204, 204));
        provincia.setText("Ingrese su provincia");
        provincia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                provinciaMousePressed(evt);
            }
        });
        provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaActionPerformed(evt);
            }
        });

        legajo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        legajo.setForeground(new java.awt.Color(204, 204, 204));
        legajo.setText("Ingrese su legajo");
        legajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                legajoMousePressed(evt);
            }
        });
        legajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legajoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Año de ingreso:");

        iconoenviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inscripcion.png"))); // NOI18N
        iconoenviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconoenviarMousePressed(evt);
            }
        });

        txtenviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtenviar.setForeground(new java.awt.Color(255, 255, 255));
        txtenviar.setText("Enviar Formulario");
        txtenviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtenviarMousePressed(evt);
            }
        });

        iconoborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar-documento.png"))); // NOI18N
        iconoborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconoborrarMousePressed(evt);
            }
        });

        txtborrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtborrar.setForeground(new java.awt.Color(255, 255, 255));
        txtborrar.setText("Borrar Formulario");
        txtborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtborrarMousePressed(evt);
            }
        });

        txtatras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtatras.setForeground(new java.awt.Color(255, 255, 255));
        txtatras.setText("Volver atrás");
        txtatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtatrasMousePressed(evt);
            }
        });

        iconatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-hacia-atras.png"))); // NOI18N
        iconatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconatrasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(233, 233, 233))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dni, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(provincia)
                                .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(legajo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(fem)
                                    .addGap(42, 42, 42)
                                    .addComponent(mas)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jRadioButton3))
                                .addComponent(apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(iconatras)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtatras))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(anioIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(carrera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(celular, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(localidad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pais, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iconoborrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtborrar)
                        .addGap(112, 112, 112)
                        .addComponent(iconoenviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtenviar)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconatras)
                            .addComponent(txtatras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(barrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(legajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mas)
                                    .addComponent(fem)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(anioIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconoenviar)
                            .addComponent(txtenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoborrar)
                            .addComponent(txtborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void localidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localidadActionPerformed

    private void dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void barrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barrioActionPerformed

    private void facultadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultadMouseClicked

    }//GEN-LAST:event_facultadMouseClicked

    private void facultadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facultadMousePressed
 
    }//GEN-LAST:event_facultadMousePressed

    private void facultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultadActionPerformed

        String selectedOption = (String) facultad.getSelectedItem();

        // Filter options for comboBox2
        switch (selectedOption) {
            case "Facultad de Ciencias Exactas y Tecnológicas" -> carrera.setModel(new DefaultComboBoxModel<>(new String[]{"Licenciatura en Sistemas de Información",
                "Técnico Universitario en Hidrología Subterránea", "Profesorado en Informática", "Técnico Universitario Vial",
                "Profesorado en Física", "Ingeniería en Agrimensura", "Técnico Universitario en Construcciones", "Ingeniería Civil",
                "Profesorado en Matemática", "Ingeniería Vial", "Licenciatura en Matemática", "Ingeniería Hidráulica", "Ingeniería Electromecánica",
                "Ingeniería Electrónica", "Ingeniería Eléctrica", "Técnico Universitario en Organización y Control de la Producción",
                "Ingeniería Industrial", "Programador Universitario en Informática", "Licenciatura en Hidrología Subterránea"}));
    case "Facultad de Ciencias Sociales y Humanidades" -> carrera.setModel(new DefaultComboBoxModel<>(new String[]{"Licenciatura en Obstetricia", "Licenciatura en Administración",
        "Licenciatura en Trabajo Social", "Licenciatura en Filosofía", "Profesorado en Educación para la Salud", "Licenciatura en Educación para la Salud",
        "Contador Público Nacional", "Licenciatura en Enfermería", "Tec. Sup. en Educación Intercultural Bilingüe", "Licenciatura en Sociología"}));
        case "Facultad de Agronomía y Agroindustria" -> carrera.setModel(new DefaultComboBoxModel<>(new String[]{"Tecnicatura Universitaria en Apicultura", "Ingeniería Agronómica",
            "Profesorado en Química", "Licenciatura en Biotecnología", "Ingeniería en Alimentos", "Licenciatura En Química"}));
case "Facultad de Ciencias Médicas" -> carrera.setModel(new DefaultComboBoxModel<>(new String[]{"Medicina"}));
default -> carrera.setModel(new DefaultComboBoxModel<>(new String[]{"Tecnicatura Universitaria Fitosanitarista", "Ingenieria Forestal",
    "Tecnicatura Universitaria en Viveros y Plantaciones Forestales", "Tecnicatura Universitaria en Aserraderos y Carpintería Industrial",
    "Ingeniería en Industrias Forestales", "Licenciatura En Ecología Y Conservación Del Ambiente", "Ingeniería en Industrias Forestales"}));
    }

    // Enable comboBox2
    carrera.setEnabled(true);
    }//GEN-LAST:event_facultadActionPerformed

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisActionPerformed

    private void provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaActionPerformed

    private void legajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legajoActionPerformed

    private void nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMousePressed
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (nombre.getText().equals("Ingrese su nombre")) {
            nombre.setText("");
            nombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombreMousePressed

    private void apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apellidoMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (apellido.getText().equals("Ingrese su apellido")) {
            apellido.setText("");
            apellido.setForeground(Color.black);
        }
    }//GEN-LAST:event_apellidoMousePressed

    private void dniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (dni.getText().equals("Ingrese su DNI")) {
            dni.setText("");
            dni.setForeground(Color.black);
        }
    }//GEN-LAST:event_dniMousePressed

    private void paisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paisMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (pais.getText().equals("Ingrese su pais")) {
            pais.setText("");
            pais.setForeground(Color.black);
        }
    }//GEN-LAST:event_paisMousePressed

    private void provinciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_provinciaMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (provincia.getText().equals("Ingrese su provincia")) {
            provincia.setText("");
            provincia.setForeground(Color.black);
        }
    }//GEN-LAST:event_provinciaMousePressed

    private void localidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_localidadMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (localidad.getText().equals("Ingrese su localidad")) {
            localidad.setText("");
            localidad.setForeground(Color.black);
        }
    }//GEN-LAST:event_localidadMousePressed

    private void barrioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barrioMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (barrio.getText().equals("Ingrese su barrio")) {
            barrio.setText("");
            barrio.setForeground(Color.black);
        }
    }//GEN-LAST:event_barrioMousePressed

    private void direccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionMousePressed
       if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (direccion.getText().equals("Ingrese su direccion")) {
            direccion.setText("");
            direccion.setForeground(Color.black);
        }
    }//GEN-LAST:event_direccionMousePressed

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }
        
        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (email.getText().equals("Ingrese su e-mail")) {
            email.setText("");
            email.setForeground(Color.black);
        }                                   
    }//GEN-LAST:event_emailMousePressed

    private void legajoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_legajoMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }
        
        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }
        
        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }
        
        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }
        
        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }
        
        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }
        
        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }
        
        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }
        
        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }
        
        if (celular.getText().isEmpty()) {
            celular.setText("Ingrese su celular");
            celular.setForeground(Color.LIGHT_GRAY);
        }

        if (legajo.getText().equals("Ingrese su legajo")) {
            legajo.setText("");
            legajo.setForeground(Color.black);
        }
    }//GEN-LAST:event_legajoMousePressed

    private void celularMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_celularMousePressed
        if (nombre.getText().isEmpty()) {
            nombre.setText("Ingrese su nombre");
            nombre.setForeground(Color.LIGHT_GRAY);
        }

        if (apellido.getText().isEmpty()) {
            apellido.setText("Ingrese su apellido");
            apellido.setForeground(Color.LIGHT_GRAY);
        }

        if (dni.getText().isEmpty()) {
            dni.setText("Ingrese su DNI");
            dni.setForeground(Color.LIGHT_GRAY);
        }

        if (pais.getText().isEmpty()) {
            pais.setText("Ingrese su pais");
            pais.setForeground(Color.LIGHT_GRAY);
        }

        if (provincia.getText().isEmpty()) {
            provincia.setText("Ingrese su provincia");
            provincia.setForeground(Color.LIGHT_GRAY);
        }

        if (barrio.getText().isEmpty()) {
            barrio.setText("Ingrese su barrio");
            barrio.setForeground(Color.LIGHT_GRAY);
        }

        if (localidad.getText().isEmpty()) {
            localidad.setText("Ingrese su localidad");
            localidad.setForeground(Color.LIGHT_GRAY);
        }

        if (direccion.getText().isEmpty()) {
            direccion.setText("Ingrese su direccion");
            direccion.setForeground(Color.LIGHT_GRAY);
        }

        if (email.getText().isEmpty()) {
            email.setText("Ingrese su e-mail");
            email.setForeground(Color.LIGHT_GRAY);
        }

        if (legajo.getText().isEmpty()) {
            legajo.setText("Ingrese su legajo");
            legajo.setForeground(Color.LIGHT_GRAY);
        }

        if (celular.getText().equals("Ingrese su celular")) {
            celular.setText("");
            celular.setForeground(Color.black);
        }
    }//GEN-LAST:event_celularMousePressed

    private void txtenviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtenviarMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Se ha registrado con éxito!.", "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_txtenviarMousePressed

    private void txtborrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtborrarMousePressed
        FormularioRegistro formreg = new FormularioRegistro();
        formreg.setVisible(true);
        formreg.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_txtborrarMousePressed

    private void txtatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtatrasMousePressed
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_txtatrasMousePressed

    private void iconatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconatrasMousePressed
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_iconatrasMousePressed

    private void iconoenviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoenviarMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Se ha registrado con éxito!.", "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_iconoenviarMousePressed

    private void iconoborrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoborrarMousePressed
        FormularioRegistro formreg = new FormularioRegistro();
        formreg.setVisible(true);
        formreg.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_iconoborrarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JYearChooser anioIng;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField barrio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> carrera;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> facultad;
    private javax.swing.JRadioButton fem;
    private javax.swing.JLabel iconatras;
    private javax.swing.JLabel iconoborrar;
    private javax.swing.JLabel iconoenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField legajo;
    private javax.swing.JTextField localidad;
    private javax.swing.JRadioButton mas;
    private com.toedter.calendar.JDateChooser nacimiento;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField provincia;
    private javax.swing.JLabel txtatras;
    private javax.swing.JLabel txtborrar;
    private javax.swing.JLabel txtenviar;
    // End of variables declaration//GEN-END:variables
}
