/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import com.toedter.calendar.JCalendar;
import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author dgera
 */
public class FormularioEstablecimiento extends javax.swing.JFrame {

    /**
     * Creates new form FormularioReg
     */
    public FormularioEstablecimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        iconoenviar = new javax.swing.JLabel();
        txtenviar = new javax.swing.JLabel();
        iconoborrar = new javax.swing.JLabel();
        txtborrar = new javax.swing.JLabel();
        txtatras = new javax.swing.JLabel();
        iconatras = new javax.swing.JLabel();
        txtpregunta5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtpregunta6 = new javax.swing.JLabel();
        txtpregunta7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        txtpregunta8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        txtpregunta9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RESERVA DE ESTABLECIMIENTO");

        iconoenviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inscripcion.png"))); // NOI18N
        iconoenviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconoenviarMousePressed(evt);
            }
        });

        txtenviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtenviar.setForeground(new java.awt.Color(255, 255, 255));
        txtenviar.setText("Enviar Reserva");
        txtenviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtenviarMousePressed(evt);
            }
        });

        iconoborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar-documento.png"))); // NOI18N
        iconoborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconoborrarMousePressed(evt);
            }
        });

        txtborrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtborrar.setForeground(new java.awt.Color(255, 255, 255));
        txtborrar.setText("Borrar Selección");
        txtborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtborrarMousePressed(evt);
            }
        });

        txtatras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtatras.setForeground(new java.awt.Color(255, 255, 255));
        txtatras.setText("Volver atrás");
        txtatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtatrasMousePressed(evt);
            }
        });

        iconatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-hacia-atras.png"))); // NOI18N
        iconatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconatrasMousePressed(evt);
            }
        });

        txtpregunta5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta5.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta5.setText("Seleccione el establecimiento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SUM", "Cancha de Futbol 11", "Quincho" }));
        jComboBox1.setSelectedIndex(-1);

        txtpregunta6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta6.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta6.setText("Seleccione una fecha:");

        txtpregunta7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta7.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta7.setText("Seleccione el N° del quincho:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quincho 1", "Quincho 2", "Quincho 3", "Quincho 4" }));
        jComboBox2.setSelectedIndex(-1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menos de 10 personas", "Entre 15 personas", "Más de 20 personas", "Hasta 30 personas" }));
        jComboBox3.setSelectedIndex(-1);

        txtpregunta8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta8.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta8.setText("Seleccione un horario del dia:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De 8:00 a 12:00", "De 12:00 a 20:00", "De 20:00 a 8:00" }));
        jComboBox4.setSelectedIndex(-1);

        txtpregunta9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta9.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta9.setText("Seleccione el N° de personas:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(iconoborrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtborrar)
                                .addGap(112, 112, 112)
                                .addComponent(iconoenviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtenviar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(559, 559, 559)
                                .addComponent(iconatras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtatras))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel5)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtpregunta5, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtpregunta6))
                .addGap(181, 181, 181)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpregunta9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtpregunta8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtpregunta7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpregunta7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpregunta6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpregunta9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(txtpregunta8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconatras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtatras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoenviar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtenviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoborrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtborrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtenviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtenviarMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Se ha registrado con éxito!.", "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_txtenviarMousePressed

    private void txtborrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtborrarMousePressed
        FormularioEstablecimiento formreg = new FormularioEstablecimiento();
        formreg.setVisible(true);
        formreg.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_txtborrarMousePressed

    private void txtatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtatrasMousePressed
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_txtatrasMousePressed

    private void iconatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconatrasMousePressed
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_iconatrasMousePressed

    private void iconoenviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoenviarMousePressed
        javax.swing.JOptionPane.showMessageDialog(this, "¡Se ha registrado con éxito!.", "Registro", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        IniciarSesion inicioS = new IniciarSesion();
        inicioS.setVisible(true);
        inicioS.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_iconoenviarMousePressed

    private void iconoborrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoborrarMousePressed
        FormularioEstablecimiento formreg = new FormularioEstablecimiento();
        formreg.setVisible(true);
        formreg.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_iconoborrarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel iconatras;
    private javax.swing.JLabel iconoborrar;
    private javax.swing.JLabel iconoenviar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtatras;
    private javax.swing.JLabel txtborrar;
    private javax.swing.JLabel txtenviar;
    private javax.swing.JLabel txtpregunta5;
    private javax.swing.JLabel txtpregunta6;
    private javax.swing.JLabel txtpregunta7;
    private javax.swing.JLabel txtpregunta8;
    private javax.swing.JLabel txtpregunta9;
    // End of variables declaration//GEN-END:variables
}
