/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package igu;

/**
 *
 * @author dgera
 */
public class MisTurnos extends javax.swing.JPanel {

    /**
     * Creates new form MisInscripcioness
     */
    public MisTurnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtcomedor4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnderechos2 = new javax.swing.JPanel();
        txtcomedor6 = new javax.swing.JLabel();
        deportes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 0));

        txtcomedor4.setBackground(new java.awt.Color(255, 255, 255));
        txtcomedor4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcomedor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcomedor4.setText("Cancelar Turno");
        txtcomedor4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtcomedor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcomedor4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtcomedor4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtcomedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Turnos Médicos");

        btnderechos2.setBackground(new java.awt.Color(255, 255, 255));
        btnderechos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtcomedor6.setBackground(new java.awt.Color(255, 255, 255));
        txtcomedor6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtcomedor6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcomedor6.setText("Reservar Turno");
        txtcomedor6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtcomedor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcomedor6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnderechos2Layout = new javax.swing.GroupLayout(btnderechos2);
        btnderechos2.setLayout(btnderechos2Layout);
        btnderechos2Layout.setHorizontalGroup(
            btnderechos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtcomedor6, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
        );
        btnderechos2Layout.setVerticalGroup(
            btnderechos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtcomedor6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        deportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cita-medica.png"))); // NOI18N
        deportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnderechos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(170, 170, 170)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deportes)
                        .addGap(232, 232, 232))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel16)
                .addGap(80, 80, 80)
                .addComponent(deportes, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnderechos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcomedor4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomedor4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomedor4MousePressed

    private void txtcomedor6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomedor6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomedor6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnderechos2;
    private javax.swing.JLabel deportes;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel txtcomedor4;
    private javax.swing.JLabel txtcomedor6;
    // End of variables declaration//GEN-END:variables
}
