/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Secretario;

import GUI.Secretario.Secretario;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import logica.Sesion;
import logica.Usuario;

/**
 *
 * @author dgera
 */
public class PrincipalSecretario extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public PrincipalSecretario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelIzq = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnInfo = new javax.swing.JPanel();
        txtInfo = new javax.swing.JLabel();
        iconInfo = new javax.swing.JLabel();
        btnpri = new javax.swing.JPanel();
        iconpri = new javax.swing.JLabel();
        txtpri = new javax.swing.JLabel();
        btnEvaluacion = new javax.swing.JPanel();
        iconEvaluacion = new javax.swing.JLabel();
        txtEvaluacion = new javax.swing.JLabel();
        btnFacturas = new javax.swing.JPanel();
        iconFacturas = new javax.swing.JLabel();
        txtFacturas = new javax.swing.JLabel();
        btnconfig = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btncerrar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fondo2.png"))); // NOI18N

        javax.swing.GroupLayout panelDerLayout = new javax.swing.GroupLayout(panelDer);
        panelDer.setLayout(panelDerLayout);
        panelDerLayout.setHorizontalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
        );
        panelDerLayout.setVerticalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 530, 540));

        panelIzq.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        btnInfo.setBackground(new java.awt.Color(175, 0, 0));
        btnInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfo.setPreferredSize(new java.awt.Dimension(270, 51));
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInfoMousePressed(evt);
            }
        });
        btnInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtInfo.setForeground(new java.awt.Color(255, 255, 255));
        txtInfo.setText("Mis informes");
        txtInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtInfo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtInfoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtInfoMousePressed(evt);
            }
        });
        btnInfo.add(txtInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        iconInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/archivo.png"))); // NOI18N
        iconInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconInfoMousePressed(evt);
            }
        });
        btnInfo.add(iconInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnpri.setBackground(new java.awt.Color(183, 52, 66));
        btnpri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpriMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpriMousePressed(evt);
            }
        });
        btnpri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconpri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconpri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home-outline.png"))); // NOI18N
        iconpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconpriMousePressed(evt);
            }
        });
        btnpri.add(iconpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        txtpri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpri.setForeground(new java.awt.Color(255, 255, 255));
        txtpri.setText("Principal");
        txtpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpriMousePressed(evt);
            }
        });
        btnpri.add(txtpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnEvaluacion.setBackground(new java.awt.Color(175, 0, 0));
        btnEvaluacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEvaluacion.setPreferredSize(new java.awt.Dimension(270, 51));
        btnEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEvaluacionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEvaluacionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEvaluacionMousePressed(evt);
            }
        });
        btnEvaluacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconEvaluacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconEvaluacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inscripcion.png"))); // NOI18N
        iconEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconEvaluacionMousePressed(evt);
            }
        });
        btnEvaluacion.add(iconEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        txtEvaluacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEvaluacion.setForeground(new java.awt.Color(255, 255, 255));
        txtEvaluacion.setText("Mis evaluaciones");
        txtEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEvaluacionMousePressed(evt);
            }
        });
        btnEvaluacion.add(txtEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnFacturas.setBackground(new java.awt.Color(175, 0, 0));
        btnFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFacturas.setPreferredSize(new java.awt.Dimension(270, 51));
        btnFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacturasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFacturasMousePressed(evt);
            }
        });
        btnFacturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/factura.png"))); // NOI18N
        iconFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconFacturasMousePressed(evt);
            }
        });
        btnFacturas.add(iconFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        txtFacturas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtFacturas.setForeground(new java.awt.Color(255, 255, 255));
        txtFacturas.setText("Mis facturas");
        txtFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFacturasMousePressed(evt);
            }
        });
        btnFacturas.add(txtFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnconfig.setBackground(new java.awt.Color(175, 0, 0));
        btnconfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconfig.setPreferredSize(new java.awt.Dimension(270, 51));
        btnconfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconfigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnconfigMousePressed(evt);
            }
        });
        btnconfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/configuraciones.png"))); // NOI18N
        btnconfig.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Configuración");
        btnconfig.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btncerrar.setBackground(new java.awt.Color(175, 0, 0));
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setPreferredSize(new java.awt.Dimension(270, 51));
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncerrarMousePressed(evt);
            }
        });
        btncerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar-sesion.png"))); // NOI18N
        btncerrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cerrar sesión");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        btncerrar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout panelIzqLayout = new javax.swing.GroupLayout(panelIzq);
        panelIzq.setLayout(panelIzqLayout);
        panelIzqLayout.setHorizontalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzqLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpri, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelIzqLayout.setVerticalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(panelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered

    }//GEN-LAST:event_btnInfoMouseEntered

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited

    }//GEN-LAST:event_btnInfoMouseExited

    private void btnInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMousePressed
        resetColor(btnpri);
        setColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisInformes p1 = new MisInformes();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnInfoMousePressed

    private void btnpriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpriMouseEntered

    }//GEN-LAST:event_btnpriMouseEntered

    private void btnpriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpriMouseExited

    }//GEN-LAST:event_btnpriMouseExited

    private void btnpriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpriMousePressed
        setColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Secretario p1 = new Secretario();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnpriMousePressed

    private void btnEvaluacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMouseEntered

    }//GEN-LAST:event_btnEvaluacionMouseEntered

    private void btnEvaluacionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMouseExited

    }//GEN-LAST:event_btnEvaluacionMouseExited

    private void btnEvaluacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMousePressed
        resetColor(btnpri);
        resetColor(btnInfo);
        setColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisEvaluaciones p1 = new MisEvaluaciones();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnEvaluacionMousePressed

    private void btnFacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseEntered

    }//GEN-LAST:event_btnFacturasMouseEntered

    private void btnFacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMouseExited
  
    }//GEN-LAST:event_btnFacturasMouseExited

    private void btnFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturasMousePressed
        resetColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        setColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisFacturas p1 = new MisFacturas();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnFacturasMousePressed

    private void btnconfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigMouseEntered

    }//GEN-LAST:event_btnconfigMouseEntered

    private void btnconfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigMouseExited

    }//GEN-LAST:event_btnconfigMouseExited

    private void btnconfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigMousePressed
        resetColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        setColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Configuracion p1 = new Configuracion();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnconfigMousePressed

    private void btncerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseEntered

    }//GEN-LAST:event_btncerrarMouseEntered

    private void btncerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseExited

    }//GEN-LAST:event_btncerrarMouseExited

    private void btncerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMousePressed
        resetColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        setColor(btncerrar);
        Sesion.cerrarSesion();
        IniciarSesion iniciarSesion = new IniciarSesion();
        iniciarSesion.setVisible(true);
        iniciarSesion.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btncerrarMousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        // TODO add your handling code here:
        resetColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        setColor(btncerrar);
        Sesion.cerrarSesion();
        IniciarSesion iniciarSesion = new IniciarSesion();
        iniciarSesion.setVisible(true);
        iniciarSesion.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel12MousePressed

    private void txtInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtInfoMousePressed
        resetColor(btnpri);
        setColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisInformes p1 = new MisInformes();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_txtInfoMousePressed

    private void txtInfoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtInfoAncestorAdded

    }//GEN-LAST:event_txtInfoAncestorAdded

    private void txtpriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpriMousePressed
        // TODO add your handling code here:
        setColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Secretario p1 = new Secretario();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_txtpriMousePressed

    private void iconpriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconpriMousePressed
        // TODO add your handling code here:
        setColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Secretario p1 = new Secretario();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_iconpriMousePressed

    private void txtEvaluacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEvaluacionMousePressed
        // TODO add your handling code here:
        resetColor(btnpri);
        resetColor(btnInfo);
        setColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisEvaluaciones p1 = new MisEvaluaciones();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_txtEvaluacionMousePressed

    private void iconEvaluacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEvaluacionMousePressed
        // TODO add your handling code here:
        resetColor(btnpri);
        resetColor(btnInfo);
        setColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisEvaluaciones p1 = new MisEvaluaciones();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_iconEvaluacionMousePressed

    private void iconFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconFacturasMousePressed
        // TODO add your handling code here:
        resetColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        setColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisFacturas p1 = new MisFacturas();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_iconFacturasMousePressed

    private void txtFacturasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFacturasMousePressed
        // TODO add your handling code here:
        resetColor(btnpri);
        resetColor(btnInfo);
        resetColor(btnEvaluacion);
        setColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisFacturas p1 = new MisFacturas();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_txtFacturasMousePressed

    private void iconInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconInfoMousePressed
        // TODO add your handling code here:
        resetColor(btnpri);
        setColor(btnInfo);
        resetColor(btnEvaluacion);
        resetColor(btnFacturas);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisInformes p1 = new MisInformes();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_iconInfoMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(183,52,66));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(175,0,0));
    }
    /**
     * @param args the command line arguments
     */
    
    

    public static javax.swing.JPanel content;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnEvaluacion;
    private javax.swing.JPanel btnFacturas;
    private javax.swing.JPanel btnInfo;
    private javax.swing.JPanel btncerrar;
    private javax.swing.JPanel btnconfig;
    private javax.swing.JPanel btnpri;
    private javax.swing.JLabel iconEvaluacion;
    private javax.swing.JLabel iconFacturas;
    private javax.swing.JLabel iconInfo;
    private javax.swing.JLabel iconpri;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JLabel txtEvaluacion;
    private javax.swing.JLabel txtFacturas;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtpri;
    // End of variables declaration//GEN-END:variables
}
