
package GUI.Estudiante;

import GUI.Estudiante.PrincipalEstudiante;
import Conexion.*;
import DAO.*;
import Tabla.*;
import VO.*;
import GUI.Empleado.*;
import GUI.Estudiante.*;
import GUI.Secretario.*;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author dgera
 */
public class FormularioBeca extends javax.swing.JFrame {

    String dirDNIPost = " ";
    String dirNegPost = " ";
    String dirIngPost = " ";
    String dirAlumRPost = " ";
    String dirCUDPost = " ";
    String dirDecPost = " ";
    String dirDNIgf = " ";
    String dirNeggf = " ";
    String dirInggf = " ";
    String estadoBeca;
    
    public FormularioBeca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelgrande = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        txtpregunta1 = new javax.swing.JLabel();
        btnsi = new javax.swing.JRadioButton();
        btnno = new javax.swing.JRadioButton();
        txtpregunta2 = new javax.swing.JLabel();
        btncasa = new javax.swing.JRadioButton();
        btndepartamento = new javax.swing.JRadioButton();
        btnresidencia = new javax.swing.JRadioButton();
        txtpregunta3 = new javax.swing.JLabel();
        padre = new javax.swing.JCheckBox();
        madre = new javax.swing.JCheckBox();
        hermane = new javax.swing.JCheckBox();
        tie = new javax.swing.JCheckBox();
        abuele = new javax.swing.JCheckBox();
        otro = new javax.swing.JCheckBox();
        txtpregunta4 = new javax.swing.JLabel();
        btnpropia = new javax.swing.JRadioButton();
        btnalquiler = new javax.swing.JRadioButton();
        btnfamiliar = new javax.swing.JRadioButton();
        txtpregunta5 = new javax.swing.JLabel();
        txtpregunta7 = new javax.swing.JLabel();
        iconoenviar = new javax.swing.JLabel();
        txtenviar = new javax.swing.JLabel();
        iconoborrar = new javax.swing.JLabel();
        txtborrar = new javax.swing.JLabel();
        txtatras = new javax.swing.JLabel();
        iconatras = new javax.swing.JLabel();
        dniE = new javax.swing.JButton();
        ingresosE = new javax.swing.JButton();
        alumnoReg = new javax.swing.JButton();
        declaracionJ = new javax.swing.JButton();
        negativaE = new javax.swing.JButton();
        cud = new javax.swing.JButton();
        dniGf = new javax.swing.JButton();
        negativaGf = new javax.swing.JButton();
        ingresosGf = new javax.swing.JButton();

        jFileChooser1.setBackground(new java.awt.Color(153, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelgrande.setBackground(new java.awt.Color(153, 0, 0));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("BECA COMEDOR UNIVERSITARIO");

        txtpregunta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta1.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta1.setText("¿Tiene ingresos?");

        btnsi.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(btnsi);
        btnsi.setForeground(new java.awt.Color(255, 255, 255));
        btnsi.setText("Si");
        btnsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiActionPerformed(evt);
            }
        });

        btnno.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup1.add(btnno);
        btnno.setForeground(new java.awt.Color(255, 255, 255));
        btnno.setText("No");
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });

        txtpregunta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta2.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta2.setText("Tipo de vivienda");

        btncasa.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup2.add(btncasa);
        btncasa.setForeground(new java.awt.Color(255, 255, 255));
        btncasa.setText("Casa");
        btncasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncasaActionPerformed(evt);
            }
        });

        btndepartamento.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup2.add(btndepartamento);
        btndepartamento.setForeground(new java.awt.Color(255, 255, 255));
        btndepartamento.setText("Departamento");

        btnresidencia.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup2.add(btnresidencia);
        btnresidencia.setForeground(new java.awt.Color(255, 255, 255));
        btnresidencia.setText("Residencia / Pensión");
        btnresidencia.setToolTipText("");
        btnresidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresidenciaActionPerformed(evt);
            }
        });

        txtpregunta3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta3.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta3.setText("Grupo familiar");

        padre.setBackground(new java.awt.Color(153, 0, 0));
        padre.setForeground(new java.awt.Color(255, 255, 255));
        padre.setText("Padre");

        madre.setBackground(new java.awt.Color(153, 0, 0));
        madre.setForeground(new java.awt.Color(255, 255, 255));
        madre.setText("Madre");

        hermane.setBackground(new java.awt.Color(153, 0, 0));
        hermane.setForeground(new java.awt.Color(255, 255, 255));
        hermane.setText("Hermano/a");
        hermane.setActionCommand("");
        hermane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hermaneActionPerformed(evt);
            }
        });

        tie.setBackground(new java.awt.Color(153, 0, 0));
        tie.setForeground(new java.awt.Color(255, 255, 255));
        tie.setText("Tio/a");

        abuele.setBackground(new java.awt.Color(153, 0, 0));
        abuele.setForeground(new java.awt.Color(255, 255, 255));
        abuele.setText("Abuelo/a");

        otro.setBackground(new java.awt.Color(153, 0, 0));
        otro.setForeground(new java.awt.Color(255, 255, 255));
        otro.setText("Otro");

        txtpregunta4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta4.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta4.setText("Condición de la vivienda");

        btnpropia.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup3.add(btnpropia);
        btnpropia.setForeground(new java.awt.Color(255, 255, 255));
        btnpropia.setText("Propia");

        btnalquiler.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup3.add(btnalquiler);
        btnalquiler.setForeground(new java.awt.Color(255, 255, 255));
        btnalquiler.setText("Alquiler");
        btnalquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalquilerActionPerformed(evt);
            }
        });

        btnfamiliar.setBackground(new java.awt.Color(153, 0, 0));
        buttonGroup3.add(btnfamiliar);
        btnfamiliar.setForeground(new java.awt.Color(255, 255, 255));
        btnfamiliar.setText("Familiar");

        txtpregunta5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta5.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta5.setText("Subir archivos postulante");

        txtpregunta7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpregunta7.setForeground(new java.awt.Color(255, 255, 255));
        txtpregunta7.setText("Subir archivos de familia");

        iconoenviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inscripcion.png"))); // NOI18N
        iconoenviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtenviar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtenviar.setForeground(new java.awt.Color(255, 255, 255));
        txtenviar.setText("Enviar Inscripción");
        txtenviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtenviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtenviarMousePressed(evt);
            }
        });

        iconoborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar-documento.png"))); // NOI18N
        iconoborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtborrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtborrar.setForeground(new java.awt.Color(255, 255, 255));
        txtborrar.setText("Borrar Formulario");
        txtborrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtborrarMousePressed(evt);
            }
        });

        txtatras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtatras.setForeground(new java.awt.Color(255, 255, 255));
        txtatras.setText("Volver atrás");
        txtatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtatrasMousePressed(evt);
            }
        });

        iconatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-hacia-atras.png"))); // NOI18N
        iconatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconatrasMousePressed(evt);
            }
        });

        dniE.setBackground(new java.awt.Color(175, 0, 0));
        dniE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dniE.setForeground(new java.awt.Color(255, 255, 255));
        dniE.setText("DNI (Ambos Lados) (*)");
        dniE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dniEMousePressed(evt);
            }
        });
        dniE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniEActionPerformed(evt);
            }
        });

        ingresosE.setBackground(new java.awt.Color(175, 0, 0));
        ingresosE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresosE.setForeground(new java.awt.Color(255, 255, 255));
        ingresosE.setText("Constancia de Ingresos (*)");
        ingresosE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresosEMousePressed(evt);
            }
        });
        ingresosE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosEActionPerformed(evt);
            }
        });

        alumnoReg.setBackground(new java.awt.Color(175, 0, 0));
        alumnoReg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alumnoReg.setForeground(new java.awt.Color(255, 255, 255));
        alumnoReg.setText("Constancia Alumno (*)");
        alumnoReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                alumnoRegMousePressed(evt);
            }
        });
        alumnoReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnoRegActionPerformed(evt);
            }
        });

        declaracionJ.setBackground(new java.awt.Color(175, 0, 0));
        declaracionJ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        declaracionJ.setForeground(new java.awt.Color(255, 255, 255));
        declaracionJ.setText("Declaración Jurada");
        declaracionJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                declaracionJMousePressed(evt);
            }
        });
        declaracionJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declaracionJActionPerformed(evt);
            }
        });

        negativaE.setBackground(new java.awt.Color(175, 0, 0));
        negativaE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        negativaE.setForeground(new java.awt.Color(255, 255, 255));
        negativaE.setText("Certificación Negativa (*)");
        negativaE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                negativaEMousePressed(evt);
            }
        });
        negativaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativaEActionPerformed(evt);
            }
        });

        cud.setBackground(new java.awt.Color(175, 0, 0));
        cud.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cud.setForeground(new java.awt.Color(255, 255, 255));
        cud.setText("C.U.D (Si lo tuviera)");
        cud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cudMousePressed(evt);
            }
        });
        cud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cudActionPerformed(evt);
            }
        });

        dniGf.setBackground(new java.awt.Color(175, 0, 0));
        dniGf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dniGf.setForeground(new java.awt.Color(255, 255, 255));
        dniGf.setText("DNI (Ambos Lados) (*)");
        dniGf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dniGfMousePressed(evt);
            }
        });
        dniGf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniGfActionPerformed(evt);
            }
        });

        negativaGf.setBackground(new java.awt.Color(175, 0, 0));
        negativaGf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        negativaGf.setForeground(new java.awt.Color(255, 255, 255));
        negativaGf.setText("Certificación Negativa (*)");
        negativaGf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                negativaGfMousePressed(evt);
            }
        });
        negativaGf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativaGfActionPerformed(evt);
            }
        });

        ingresosGf.setBackground(new java.awt.Color(175, 0, 0));
        ingresosGf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ingresosGf.setForeground(new java.awt.Color(255, 255, 255));
        ingresosGf.setText("Constancia de Ingresos");
        ingresosGf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresosGfMousePressed(evt);
            }
        });
        ingresosGf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresosGfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelgrandeLayout = new javax.swing.GroupLayout(panelgrande);
        panelgrande.setLayout(panelgrandeLayout);
        panelgrandeLayout.setHorizontalGroup(
            panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgrandeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelgrandeLayout.createSequentialGroup()
                        .addComponent(txtpregunta5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelgrandeLayout.createSequentialGroup()
                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelgrandeLayout.createSequentialGroup()
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpregunta1)
                                    .addComponent(btnsi)
                                    .addComponent(btnno))
                                .addGap(47, 47, 47)
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelgrandeLayout.createSequentialGroup()
                                        .addComponent(txtpregunta2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtpregunta4)
                                        .addGap(40, 40, 40))
                                    .addGroup(panelgrandeLayout.createSequentialGroup()
                                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(titulo)
                                            .addGroup(panelgrandeLayout.createSequentialGroup()
                                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btncasa)
                                                    .addComponent(btnresidencia)
                                                    .addComponent(btndepartamento))
                                                .addGap(73, 73, 73)
                                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnpropia)
                                                    .addComponent(btnalquiler)
                                                    .addComponent(btnfamiliar))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelgrandeLayout.createSequentialGroup()
                                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(padre)
                                            .addComponent(madre)
                                            .addComponent(hermane))
                                        .addGap(21, 21, 21)
                                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(otro)
                                            .addComponent(abuele)
                                            .addComponent(tie)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelgrandeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtpregunta3)
                                        .addGap(59, 59, 59))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelgrandeLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(iconoborrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtborrar)
                                .addGap(118, 118, 118)
                                .addComponent(iconoenviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtenviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconatras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtatras)
                                .addGap(39, 39, 39))
                            .addComponent(txtpregunta7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelgrandeLayout.createSequentialGroup()
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dniGf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dniE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ingresosE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(negativaGf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(declaracionJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(alumnoReg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ingresosGf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(negativaE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(48, 48, 48))))
        );
        panelgrandeLayout.setVerticalGroup(
            panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgrandeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelgrandeLayout.createSequentialGroup()
                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelgrandeLayout.createSequentialGroup()
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnpropia)
                                    .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(padre)
                                        .addComponent(tie)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(madre)
                                    .addComponent(abuele)
                                    .addComponent(btnalquiler))
                                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelgrandeLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(hermane)
                                            .addComponent(otro)))
                                    .addGroup(panelgrandeLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnfamiliar))))
                            .addGroup(panelgrandeLayout.createSequentialGroup()
                                .addComponent(btncasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndepartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnresidencia))))
                    .addGroup(panelgrandeLayout.createSequentialGroup()
                        .addComponent(txtpregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnno)))
                .addGap(18, 18, 18)
                .addComponent(txtpregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelgrandeLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ingresosE))
                    .addComponent(dniE)
                    .addGroup(panelgrandeLayout.createSequentialGroup()
                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(negativaE)
                            .addComponent(alumnoReg))
                        .addGap(23, 23, 23)
                        .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cud)
                            .addComponent(declaracionJ))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(txtpregunta7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dniGf)
                    .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(negativaGf)
                        .addComponent(ingresosGf)))
                .addGap(40, 40, 40)
                .addGroup(panelgrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoenviar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtenviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconoborrar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtborrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconatras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtatras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        getContentPane().add(panelgrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncasaActionPerformed

    private void hermaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hermaneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hermaneActionPerformed

    private void btnresidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnresidenciaActionPerformed

    private void btnalquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalquilerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnalquilerActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed

    }//GEN-LAST:event_btnnoActionPerformed

    private void btnsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiActionPerformed

    }//GEN-LAST:event_btnsiActionPerformed

    private void txtatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtatrasMousePressed
        PrincipalEstudiante principalE = new PrincipalEstudiante();
        principalE.setVisible(true);
        principalE.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_txtatrasMousePressed

    private void iconatrasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconatrasMousePressed
        PrincipalEstudiante principalE = new PrincipalEstudiante();
        principalE.setVisible(true);
        principalE.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        // Opcional: Cerrar el JFrame actual
        this.dispose();
    }//GEN-LAST:event_iconatrasMousePressed

    private void txtborrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtborrarMousePressed
        FormularioBeca formbeca = new FormularioBeca();
        formbeca.setVisible(true);
        formbeca.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_txtborrarMousePressed

    private void txtenviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtenviarMousePressed
        /*Usuario usuarioActivo = Sesion.getUsuarioActual();
        System.out.println(dirDNIPost + dirNegPost + dirIngPost + dirAlumRPost + dirDNIgf + dirNeggf);
        if (!" ".equals(dirDNIPost) && !" ".equals(dirNegPost) && !" ".equals(dirIngPost) && !" ".equals(dirAlumRPost) && 
                !" ".equals(dirDNIgf) && !" ".equals(dirNeggf)) {
            Conexion conn = new Conexion();
            
            String ingreso;
            if (btnno.isSelected()){
                ingreso = "No";
            }else{
                ingreso = "Si";
            }
            
            String tipoVivienda;
            if (btncasa.isSelected()){
                tipoVivienda = "Casa";
            }else if(btndepartamento.isSelected()){
                tipoVivienda = "Departamento";
            }else{
                tipoVivienda = "Departamento";
            }
            
            String condicionVivienda;
            if (btnpropia.isSelected()){
                condicionVivienda = "Propia";
            }else if(btnalquiler.isSelected()){
                condicionVivienda = "Alquiler";
            }else{
                condicionVivienda = "Familiar";
            }
            
            String grupoFamiliar = "";
            if (padre.isSelected()){
                grupoFamiliar = grupoFamiliar + "Padre ";
            }
            if (madre.isSelected()){
                grupoFamiliar = grupoFamiliar + "Madre ";
            }
            if (hermane.isSelected()){
                grupoFamiliar = grupoFamiliar + "Hermano/a ";
            }
            if (tie.isSelected()){
                grupoFamiliar = grupoFamiliar + "Tio/a ";
            }
            if (abuele.isSelected()){
                grupoFamiliar = grupoFamiliar + "Abuelo/a ";
            }
            if (otro.isSelected()){
                grupoFamiliar = grupoFamiliar + "Otro ";
            }
            
            estadoBeca = "En evaluación";
            conn.enviarFormulario(usuarioActivo.getUsername(), estadoBeca, ingreso, tipoVivienda, condicionVivienda, grupoFamiliar, dirDNIPost, dirAlumRPost, dirNegPost, dirIngPost, dirDecPost, dirCUDPost, dirDNIgf, dirNeggf, dirInggf);
            javax.swing.JOptionPane.showMessageDialog(this, "¡Inscripción registrada con éxito!.", "FORMULARIO BECA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            PrincipalEstudiante principalE = new PrincipalEstudiante();
            principalE.setVisible(true);
            principalE.setLocationRelativeTo(null);
            this.setVisible(false);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
            "¡Error al registrar inscripción!\nPor favor, complete todos los campos obligatorios (*).", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_txtenviarMousePressed

    private void dniEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniEActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirDNIPost = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_dniEActionPerformed

    private void dniEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniEMousePressed

    }//GEN-LAST:event_dniEMousePressed

    private void ingresosEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresosEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresosEMousePressed

    private void ingresosEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosEActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirIngPost = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_ingresosEActionPerformed

    private void alumnoRegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnoRegMousePressed

    }//GEN-LAST:event_alumnoRegMousePressed

    private void alumnoRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnoRegActionPerformed
       int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirAlumRPost = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_alumnoRegActionPerformed

    private void declaracionJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_declaracionJMousePressed

    }//GEN-LAST:event_declaracionJMousePressed

    private void declaracionJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declaracionJActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirDecPost = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_declaracionJActionPerformed

    private void negativaEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negativaEMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_negativaEMousePressed

    private void negativaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativaEActionPerformed
       int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirNegPost = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_negativaEActionPerformed

    private void cudMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cudMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cudMousePressed

    private void cudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cudActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirCUDPost = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_cudActionPerformed

    private void dniGfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniGfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniGfMousePressed

    private void dniGfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniGfActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirDNIgf = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_dniGfActionPerformed

    private void negativaGfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negativaGfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_negativaGfMousePressed

    private void negativaGfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativaGfActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirNeggf = nombreArchivo; // Guarda solo el nombre del archivo en dirDNIPost
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_negativaGfActionPerformed

    private void ingresosGfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresosGfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresosGfMousePressed

    private void ingresosGfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresosGfActionPerformed
        int returnValue = jFileChooser1.showOpenDialog(this);
    
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            java.io.File file = jFileChooser1.getSelectedFile();
            String nombreArchivo = file.getName(); // Obtiene solo el nombre del archivo
    
            System.out.println("Archivo seleccionado: " + nombreArchivo);
            dirInggf = nombreArchivo;
            
        } else {
            System.out.println("El usuario canceló la selección de archivo.");
        }
    }//GEN-LAST:event_ingresosGfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox abuele;
    private javax.swing.JButton alumnoReg;
    private javax.swing.JRadioButton btnalquiler;
    private javax.swing.JRadioButton btncasa;
    private javax.swing.JRadioButton btndepartamento;
    private javax.swing.JRadioButton btnfamiliar;
    private javax.swing.JRadioButton btnno;
    private javax.swing.JRadioButton btnpropia;
    private javax.swing.JRadioButton btnresidencia;
    private javax.swing.JRadioButton btnsi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cud;
    private javax.swing.JButton declaracionJ;
    private javax.swing.JButton dniE;
    private javax.swing.JButton dniGf;
    private javax.swing.JCheckBox hermane;
    private javax.swing.JLabel iconatras;
    private javax.swing.JLabel iconoborrar;
    private javax.swing.JLabel iconoenviar;
    private javax.swing.JButton ingresosE;
    private javax.swing.JButton ingresosGf;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox madre;
    private javax.swing.JButton negativaE;
    private javax.swing.JButton negativaGf;
    private javax.swing.JCheckBox otro;
    private javax.swing.JCheckBox padre;
    private javax.swing.JPanel panelgrande;
    private javax.swing.JCheckBox tie;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtatras;
    private javax.swing.JLabel txtborrar;
    private javax.swing.JLabel txtenviar;
    private javax.swing.JLabel txtpregunta1;
    private javax.swing.JLabel txtpregunta2;
    private javax.swing.JLabel txtpregunta3;
    private javax.swing.JLabel txtpregunta4;
    private javax.swing.JLabel txtpregunta5;
    private javax.swing.JLabel txtpregunta7;
    // End of variables declaration//GEN-END:variables
}
