/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.Estudiante;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import Conexion.*;
import DAO.*;
import Tabla.*;
import VO.*;
import GUI.Empleado.*;
import GUI.Estudiante.*;
import GUI.IniciarSesion;
import GUI.Secretario.*;
import java.util.ArrayList;


/**
 *
 * @author dgera
 */
public class MisReservas extends javax.swing.JPanel {

    /**
     * Creates new form MisInscripcioness
     */
    public MisReservas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnderechos = new javax.swing.JPanel();
        txtcomedor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtcomedor2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtcomedor3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(153, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/restaurante.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Viandas Diarias");

        btnderechos.setBackground(new java.awt.Color(255, 255, 255));
        btnderechos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnderechos.setPreferredSize(new java.awt.Dimension(128, 50));

        txtcomedor.setBackground(new java.awt.Color(255, 255, 255));
        txtcomedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtcomedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcomedor.setText("Cancelar Vianda");
        txtcomedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtcomedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcomedorMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnderechosLayout = new javax.swing.GroupLayout(btnderechos);
        btnderechos.setLayout(btnderechosLayout);
        btnderechosLayout.setHorizontalGroup(
            btnderechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnderechosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtcomedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        btnderechosLayout.setVerticalGroup(
            btnderechosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnderechosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcomedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtcomedor2.setBackground(new java.awt.Color(255, 255, 255));
        txtcomedor2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtcomedor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcomedor2.setText("Retroalimentación");
        txtcomedor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtcomedor2.setPreferredSize(new java.awt.Dimension(128, 50));
        txtcomedor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcomedor2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtcomedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcomedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtcomedor3.setBackground(new java.awt.Color(255, 255, 255));
        txtcomedor3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtcomedor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtcomedor3.setText("Reservar Vianda");
        txtcomedor3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtcomedor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtcomedor3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtcomedor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtcomedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnderechos, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnderechos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

    }//GEN-LAST:event_jLabel1MousePressed

    private void txtcomedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomedorMousePressed
        UsuarioVO usuarioActivo=IniciarSesion.cuenta;
        ReservaviandaDAO reserva= new ReservaviandaDAO();
        ArrayList<ReservaviandaVO> list = reserva.buscarReserva(usuarioActivo.getNombreUsuario());
         if(list.size()> 0){
            ReservaviandaVO re= new ReservaviandaVO();
            re=list.get(0);
             if(re.getCancelada().equals("si")){
                 CancelarVianda cancel = new CancelarVianda();
                cancel.setVisible(true);
                cancel.setLocationRelativeTo(null);
                 // Ocultar el JFrame actual
                 this.setVisible(false);
                 // Opcional: Cerrar el JFrame actual
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                    if (frame != null) {
                        frame.setVisible(false);
                        frame.dispose();
                    } 

                 }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Ya no puede cancelar","", javax.swing.JOptionPane.INFORMATION_MESSAGE);}
            }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Usted no reservo en el dia de la fecha","", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
     
    }//GEN-LAST:event_txtcomedorMousePressed

    private void txtcomedor3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomedor3MousePressed
        UsuarioVO usuarioActivo=IniciarSesion.cuenta;
        ReservaviandaDAO reserva= new ReservaviandaDAO();
         ArrayList<ReservaviandaVO> list = reserva.buscarReserva(usuarioActivo.getNombreUsuario());
          if(list.size()==0){
                   
            System.out.println("NOexisteReservaVianda");
            ReservaVianda reser = new ReservaVianda();
            reser.setVisible(true);
            reser.setLocationRelativeTo(null);
            // Ocultar el JFrame actual
            this.setVisible(false);
            // Opcional: Cerrar el JFrame actual

            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            if (frame != null) {
                frame.setVisible(false);
                frame.dispose();
            }
        }else{

            javax.swing.JOptionPane.showMessageDialog(this, "Usted ya ha realizado su reserva en el dia de la fecha","con exito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
             
       
            
    }//GEN-LAST:event_txtcomedor3MousePressed

    private void txtcomedor2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcomedor2MousePressed
         UsuarioVO usuarioActivo=IniciarSesion.cuenta;
        ReservaviandaDAO reserva= new ReservaviandaDAO();
        ArrayList<ReservaviandaVO> list = reserva.buscarReserva(usuarioActivo.getNombreUsuario());
        if(list.size()> 0){
            ReservaviandaVO re= new ReservaviandaVO();
            re=list.get(0);
             if(re.getCalificacion().equals(null) || re.getOpinion().equals(null)){
                RetroalimentacionVianda retro = new RetroalimentacionVianda();
                retro.setVisible(true);
                retro.setLocationRelativeTo(null);
                // Ocultar el JFrame actual
                this.setVisible(false);
                // Opcional: Cerrar el JFrame actual
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                if (frame != null) {
                    frame.setVisible(false);
                    frame.dispose();
                }
                }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Ya no puede calificar/opinar","", javax.swing.JOptionPane.INFORMATION_MESSAGE);}
            }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Usted no reservo en el dia de la fecha","", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtcomedor2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnderechos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtcomedor;
    private javax.swing.JLabel txtcomedor2;
    private javax.swing.JLabel txtcomedor3;
    // End of variables declaration//GEN-END:variables
}
