/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.Estudiante;

import GUI.Estudiante.Principal;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import logica.Sesion;
import logica.Usuario;

/**
 *
 * @author dgera
 */
public class PrincipalEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public PrincipalEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelIzq = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btninscr = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnpri = new javax.swing.JPanel();
        iconpri = new javax.swing.JLabel();
        txtpri = new javax.swing.JLabel();
        btnreservas = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnturnos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnconfig = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btncerrar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chicas.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout panelDerLayout = new javax.swing.GroupLayout(panelDer);
        panelDer.setLayout(panelDerLayout);
        panelDerLayout.setHorizontalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 530, Short.MAX_VALUE)
        );
        panelDerLayout.setVerticalGroup(
            panelDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 530, 540));

        panelIzq.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N

        btninscr.setBackground(new java.awt.Color(175, 0, 0));
        btninscr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btninscr.setPreferredSize(new java.awt.Dimension(270, 51));
        btninscr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btninscrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btninscrMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btninscrMousePressed(evt);
            }
        });
        btninscr.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/archivo.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        btninscr.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mis inscripciones");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel14AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        btninscr.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnpri.setBackground(new java.awt.Color(183, 52, 66));
        btnpri.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpriMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpriMousePressed(evt);
            }
        });
        btnpri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconpri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconpri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home-outline.png"))); // NOI18N
        iconpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                iconpriMousePressed(evt);
            }
        });
        btnpri.add(iconpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        txtpri.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpri.setForeground(new java.awt.Color(255, 255, 255));
        txtpri.setText("Principal");
        txtpri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpriMousePressed(evt);
            }
        });
        btnpri.add(txtpri, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnreservas.setBackground(new java.awt.Color(175, 0, 0));
        btnreservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreservas.setPreferredSize(new java.awt.Dimension(270, 51));
        btnreservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnreservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreservasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnreservasMousePressed(evt);
            }
        });
        btnreservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/calendar-plus.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        btnreservas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mis reservas");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        btnreservas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnturnos.setBackground(new java.awt.Color(175, 0, 0));
        btnturnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnturnos.setPreferredSize(new java.awt.Dimension(270, 51));
        btnturnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnturnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnturnosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnturnosMousePressed(evt);
            }
        });
        btnturnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/asistencia-medica.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        btnturnos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mis turnos");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        btnturnos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btnconfig.setBackground(new java.awt.Color(175, 0, 0));
        btnconfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconfig.setPreferredSize(new java.awt.Dimension(270, 51));
        btnconfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnconfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnconfigMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnconfigMousePressed(evt);
            }
        });
        btnconfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/configuraciones.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        btnconfig.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Configuración");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        btnconfig.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        btncerrar.setBackground(new java.awt.Color(175, 0, 0));
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setPreferredSize(new java.awt.Dimension(270, 51));
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncerrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncerrarMousePressed(evt);
            }
        });
        btncerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar-sesion.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        btncerrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cerrar sesión");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        btncerrar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout panelIzqLayout = new javax.swing.GroupLayout(panelIzq);
        panelIzq.setLayout(panelIzqLayout);
        panelIzqLayout.setHorizontalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIzqLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpri, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btninscr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnturnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelIzqLayout.setVerticalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpri, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btninscr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnturnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIzqLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnreservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        getContentPane().add(panelIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninscrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninscrMouseEntered

    }//GEN-LAST:event_btninscrMouseEntered

    private void btninscrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninscrMouseExited

    }//GEN-LAST:event_btninscrMouseExited

    private void btninscrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninscrMousePressed
        resetColor(btnpri);
        setColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisInscripciones p1 = new MisInscripciones();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btninscrMousePressed

    private void btnpriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpriMouseEntered

    }//GEN-LAST:event_btnpriMouseEntered

    private void btnpriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpriMouseExited

    }//GEN-LAST:event_btnpriMouseExited

    private void btnpriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpriMousePressed
        setColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Principal p1 = new Principal();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnpriMousePressed

    private void btnreservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreservasMouseEntered

    }//GEN-LAST:event_btnreservasMouseEntered

    private void btnreservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreservasMouseExited

    }//GEN-LAST:event_btnreservasMouseExited

    private void btnreservasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreservasMousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        setColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisReservas p1 = new MisReservas();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnreservasMousePressed

    private void btnturnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnturnosMouseEntered

    }//GEN-LAST:event_btnturnosMouseEntered

    private void btnturnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnturnosMouseExited
  
    }//GEN-LAST:event_btnturnosMouseExited

    private void btnturnosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnturnosMousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        setColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisTurnos p1 = new MisTurnos();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnturnosMousePressed

    private void btnconfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigMouseEntered

    }//GEN-LAST:event_btnconfigMouseEntered

    private void btnconfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigMouseExited

    }//GEN-LAST:event_btnconfigMouseExited

    private void btnconfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfigMousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        setColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Configuracion p1 = new Configuracion();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_btnconfigMousePressed

    private void btncerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseEntered

    }//GEN-LAST:event_btncerrarMouseEntered

    private void btncerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseExited

    }//GEN-LAST:event_btncerrarMouseExited

    private void btncerrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        setColor(btncerrar);
        Sesion.cerrarSesion();
        IniciarSesion iniciarSesion = new IniciarSesion();
        iniciarSesion.setVisible(true);
        iniciarSesion.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btncerrarMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        resetColor(btnpri);
        setColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisInscripciones p1 = new MisInscripciones();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        setColor(btncerrar);
        Sesion.cerrarSesion();
        IniciarSesion iniciarSesion = new IniciarSesion();
        iniciarSesion.setVisible(true);
        iniciarSesion.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        resetColor(btnpri);
        setColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisInscripciones p1 = new MisInscripciones();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel14AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel14AncestorAdded

    }//GEN-LAST:event_jLabel14AncestorAdded

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnconfig);
        resetColor(btnturnos);
        setColor(btnreservas);
        resetColor(btncerrar);
        // Abrir sección
        MisReservas p1 = new MisReservas();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        setColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisReservas p1 = new MisReservas();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel3MousePressed

    private void txtpriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpriMousePressed
        setColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Principal p1 = new Principal();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_txtpriMousePressed

    private void iconpriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconpriMousePressed
        setColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Principal p1 = new Principal();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_iconpriMousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        setColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisTurnos p1 = new MisTurnos();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        setColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        MisTurnos p1 = new MisTurnos();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        setColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Configuracion p1 = new Configuracion();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        setColor(btnconfig);
        resetColor(btncerrar);
        // Abrir sección
        Configuracion p1 = new Configuracion();
        p1.setSize(530, 540);
        p1.setLocation(0,0);

        panelDer.removeAll();
        panelDer.add(p1, BorderLayout.CENTER);
        panelDer.revalidate();
        panelDer.repaint();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        resetColor(btnpri);
        resetColor(btninscr);
        resetColor(btnreservas);
        resetColor(btnturnos);
        resetColor(btnconfig);
        setColor(btncerrar);
        Sesion.cerrarSesion();
        IniciarSesion iniciarSesion = new IniciarSesion();
        iniciarSesion.setVisible(true);
        iniciarSesion.setLocationRelativeTo(null);
        // Ocultar el JFrame actual
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel11MousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(183,52,66));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(175,0,0));
    }
    /**
     * @param args the command line arguments
     */
    
    

    public static javax.swing.JPanel content;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btncerrar;
    private javax.swing.JPanel btnconfig;
    private javax.swing.JPanel btninscr;
    private javax.swing.JPanel btnpri;
    private javax.swing.JPanel btnreservas;
    private javax.swing.JPanel btnturnos;
    private javax.swing.JLabel iconpri;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelIzq;
    private javax.swing.JLabel txtpri;
    // End of variables declaration//GEN-END:variables

}
